# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-28 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
    ]
