# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_portal', '0002_auto_20160327_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmember',
            name='qb_code',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
