# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_portal', '0003_auto_20160408_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='rep_verified',
            field=models.BooleanField(default=False),
        ),
    ]
